src/OrderBookDemoUI/Models/ErrorViewModel.cs
using System;

namespace OrderBookDemoUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/OrderBookDemoUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OrderBookDemoUI.Models;

namespace OrderBookDemoUI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/OrderBookDemoUI/Controllers/OrderBookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace OrderBookDemoUI.Controllers
{
    public class OrderBookController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/OrderBookDemoUI/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace OrderBookDemoUI.Controllers
{
    public class OrdersController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/OrderBookDemoUI/Controllers/TradesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace OrderBookDemoUI.Controllers
{
    public class TradesController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/OrderBookDemoUI/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/OrderBookDemoUI/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/OrderBookDemoUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-12">
        <h1>B.O.B.</h1>
        <h2>Basic Order Book</h2>
        <a id="AnchorGetOrders">Get Orders</a> - <code id="CodeResponse"> &nbsp; </code>
    </div>
</div>

@section Scripts{

    <script>
        $(document).ready(function () {
            $("#AnchorGetOrders").click(function () {
                $("#CodeResponse").text(' - ');
                $.getJSON(getWebServiceUri('orders'), {}, function (data) {
                    $("#CodeResponse").text(data);
                });
            });
        });

    </script>

}

src/OrderBookDemoUI/Views/OrderBook/Index.cshtml
@*@page
    @model IndexModel*@

<h1>Order Book</h1>

<hr />

<div class="row">
    <div class="col-md-6">
        <h3>Bids</h3>
        <div>
            <table class="table table-striped table-hover table-bordered">
                <thead>
                    <tr>
                        <th>Max Price</th>
                        <th>Quantity</th>
                        <th>Remaining Quantity</th>
                    </tr>
                </thead>
                <tbody id="TBodyBids">
                    <tr>
                        <td colspan="3">No Data</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-md-6">
        <h3>Asks</h3>
        <div>

            <table class="table table-striped table-hover table-bordered">
                <thead>
                    <tr>
                        <th>Min Price</th>
                        <th>Quantity</th>
                        <th>Remaining Quantity</th>
                    </tr>
                </thead>
                <tbody id="TBodyAsks">
                    <tr>
                        <td colspan="3">No Data</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts{
    <script src="scripts/signalr-client.js"></script>
    <script>
        $(document).ready(function() {
            let connection = getSignalRConnection('order-book');

            connection.on('send',
                data => {
                    console.log(data);
                    if (data.PendingAsks != null) {
                        processOrderBook(data);
                    }
                });

            connection.start()
                .then(() => {
                        connection.invoke('send', 'Hello');
                        getOrderBook();
                    }
                );
        });

        function getOrderBook() {
            $.getJSON(getWebServiceUri('orders'), {}, function() {});
        }

        function processOrderBook(orderBook) {
            var asks = orderBook.PendingAsks;
            var bids = orderBook.PendingBids;

            $("#TBodyAsks").text('');
            $("#TBodyBids").text('');

            for (var i = 0; i < asks.length; i++) {
                var tr = $("<tr />");
                $(tr).append($("<td />").text(asks[i].Price));
                $(tr).append($("<td />").text(asks[i].Quantity));
                $(tr).append($("<td />").text(asks[i].RemainingQuantity));
                $("#TBodyAsks").append(tr);
            }

            for (var i = 0; i < bids.length; i++) {
                var tr = $("<tr />");
                $(tr).append($("<td />").text(bids[i].Price));
                $(tr).append($("<td />").text(bids[i].Quantity));
                $(tr).append($("<td />").text(bids[i].RemainingQuantity));
                $("#TBodyBids").append(tr);
            }
        }

        function getSignalRConnection(hubName) {
            return new signalR.HubConnection(getWebServiceHub(hubName));
        }
    </script>
}

src/OrderBookDemoUI/Views/Orders/Index.cshtml
@*@page
    @model IndexModel*@

<h1>Orders</h1>

<div class="form-group">
    <label for="InputTraderName">Trader Name</label>
    <input class="form-control" type="text" id="InputTraderName" name="party" value="" placeholder="Trader Name" />
</div>

<hr />

<div class="row">
    <div class="col-md-6">
        <a href="javascript:void(0);" id="AnchorSelectBuy" class="btn btn-default btn-block">Buy</a>
    </div>
    <div class="col-md-6">
        <a href="javascript:void(0);" id="AnchorSelectSell" class="btn btn-default btn-block">Sell</a>
    </div>
</div>

<hr />

<div id="DivBuy" class="row">
    <div class="col-md-12">
        <form>
            <div class="form-group">
                <label for="InputBuyQuantity">Quantity</label>
                <input class="form-control" type="number" id="InputBuyQuantity" name="quantity" value="" placeholder="Quantity" />
            </div>
            <div class="form-group">
                <label for="InputBuyPrice">Max Price</label>
                <input class="form-control" type="number" id="InputBuyPrice" name="priceLimit" value="" placeholder="Max Price" />
            </div>
            <div class="form-group-lg">
                <a href="javascript:void(0);" id="AnchorBuyButton" class="btn btn-primary">Buy Now</a>
            </div>
        </form>
    </div>
</div>

<div id="DivSell" class="row">
    <div class="col-md-12">
        <form>
            <div class="form-group">
                <label for="InputSellQuantity">Quantity</label>
                <input class="form-control" type="number" id="InputSellQuantity" name="quantity" value="" placeholder="Quantity" />
            </div>
            <div class="form-group">
                <label for="InputSellPrice">Min Price</label>
                <input class="form-control" type="number" id="InputSellPrice" name="priceLimit" value="" placeholder="Min Price" />
            </div>
            <div class="form-group-lg">
                <a href="javascript:void(0);" id="AnchorSellButton" class="btn btn-info">Sell Now</a>
            </div>
        </form>
    </div>
</div>

@section Scripts{

    <script>
        var SIDE_BID = "bid"; // Buy
        var SIDE_ASK = "ask"; // Sell

        function getRandomArbitrary(min, max) {
            return Math.floor(Math.random() * (max - min) + min);
        }


        $(document).ready(function () {
            initialiseAnchors();

            var rand = getRandomArbitrary(0, Parties.length);
            $("#InputTraderName").val(Parties[rand]);

            $("#AnchorSelectBuy").click();
        });

        function initialiseAnchors() {
            $("#AnchorSelectBuy").click(function () {
                $(this).removeClass("btn-default")
                    .addClass("btn-primary");

                $("#AnchorSelectSell").addClass("btn-default")
                    .removeClass("btn-info");

                $("#DivBuy").show();
                $("#DivSell").hide();
            });

            $("#AnchorSelectSell").click(function () {
                $(this).removeClass("btn-default")
                    .addClass("btn-info");

                $("#AnchorSelectBuy").addClass("btn-default")
                    .removeClass("btn-primary");

                $("#DivSell").show();
                $("#DivBuy").hide();
            });

            $("#AnchorBuyButton").click(function () {
                placeOrder(SIDE_BID);
            });

            $("#AnchorSellButton").click(function () {
                placeOrder(SIDE_ASK);
            });
        }

        function placeOrder(side) {
            var orderValues = getOrderValues(side);
            console.log(orderValues);

            $.ajax({
                url: getWebServiceUri('orders'),
                type: "POST",
                data: JSON.stringify(orderValues),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    alert("Success!\nOrder Number: " + data);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Error\nResponse Status: ' + xhr.status + '\nError Message: ' + thrownError);
                }
            });
        }

        function getOrderValues(side) {
            var order = {
                side: side,
                party: $("#InputTraderName").val()
            };

            if (side == SIDE_ASK) {
                order.priceLimit = $("#DivSell").find("input[name=priceLimit]").val();
                order.quantity = $("#DivSell").find("input[name=quantity]").val();
            } else {
                order.priceLimit = $("#DivBuy").find("input[name=priceLimit]").val();
                order.quantity = $("#DivBuy").find("input[name=quantity]").val();
            }

            return order;
        }

        var Parties =
            "Noah,Liam,Sophia,Mason,Ava,Jacob,William,Isabella,Ethan,Mia,James,Alexander,Michael,Logan,Benjamin,Elijah,Aiden,Daniel,Matthew,Abigail,Lucas,Jackson"
                .split(',');

    </script>

}

src/OrderBookDemoUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OrderBookDemoUI</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">OrderBookDemoUI</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Orders" asp-action="Index">Orders</a></li>
                    <li><a asp-area="" asp-controller="OrderBook" asp-action="Index">Order Book</a></li>
                    <li><a asp-area="" asp-controller="Trades" asp-action="Index">Trades</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - OrderBookDemoUI</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

src/OrderBookDemoUI/Views/Trades/Index.cshtml
<h1>Trades</h1>

<hr />

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped table-hover table-bordered">
            <thead>
                <tr>
                    @*<th>Trade ID</th>*@
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Bid</th>
                    <th>Ask</th>
                </tr>
            </thead>
            <tbody id="TBodyTrades">
                <tr>
                    <td colspan="4" id="TdNoData">No Data</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

@section Scripts{
    <script src="scripts/signalr-client.js"></script>
    <script>
        $(document).ready(function () {
            let connection = getSignalRConnection('trades');

            connection.on('trade',
                data => {
                    console.log(data);
                    if (data != null && data.length > 0) {
                        for (var i = 0; i < data.length; i++) {
                            if (data[i].Quantity != null) {
                                processTrade(data[i]);
                            }
                        }
                    }
                });

            connection.start()
                .then(() => {
                    connection.invoke('trade',
                        {
                            tradeId: 1,
                            quantity: 10,
                            price: 14.4
                        }
                    );
                }
            );

            //tradeEvent({
            //    TradeId: 1,
            //    Quantity: 10,
            //    Price: 14.4
            //});
        });

        function processTrade(trade) {
            $("#TdNoData").hide(); 

            var tr = $("<tr />");
            //$(tr).append($("<td />").text(trade.TradeId));
            $(tr).append($("<td />").text(trade.Quantity));
            $(tr).append($("<td />").text(trade.Price));
            $(tr).append($("<td />").append(getOrder(trade.AskOrder, "ask")));
            $(tr).append($("<td />").append(getOrder(trade.BidOrder, "bid")));

            $("#TBodyTrades").prepend(tr);
        }

        function getOrder(order, side) {
            var div = $("<div />");
            $(div).append($("<div />").append($("<strong />").text(order.Party)));
            $(div).append($("<div />").append($("<span />").text("Quantity: ")).append($("<strong />").text(order.Quantity)));
            $(div).append($("<div />").append($("<span />").text(side == "ask" ? "Min Price: " : "Max Price: ")).append($("<strong />").html("&pound;" + order.PriceLimit)));
            return div; 
        }

        function getSignalRConnection(hubName) {
            return new signalR.HubConnection(getWebServiceHub(hubName));
        }
    </script>
}